package org.yanoproject.ledger.conformance.blueprint;

import org.yanoproject.ledger.conformance.ConformanceSettings;
import org.yanoproject.ledger.rules.fixtures.blueprint.BlueprintVectorLoader;
import org.yanoproject.ledger.rules.fixtures.blueprint.NewEpochStateDecoder;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * Renders the blueprint-vector gate's results ({@code build/conformance/blueprint-vectors.md}, and under
 * {@code conformanceReport} {@code ledger-conformance/docs/blueprint-vectors-2026-09.md}).
 */
public final class BlueprintReport {

    /**
     * A vector Amaru passes that the Java engine does not, with why.
     *
     * @param kind     {@code harness} (the harness, not the engine, is the cause) or {@code open engine finding}
     * @param evidence the explanation, with Haskell references
     */
    public record Recorded(String kind, String evidence) {
    }

    private final BlueprintVectorResults.Run run;
    private final Set<String> amaruFailures;
    private final Map<String, Recorded> recorded;

    public BlueprintReport(BlueprintVectorResults.Run run, Set<String> amaruFailures, Map<String, Recorded> recorded) {
        this.run = run;
        this.amaruFailures = amaruFailures;
        this.recorded = recorded;
    }

    public String toMarkdown() {
        List<BlueprintVectorRunner.VectorResult> results = run.results();
        StringBuilder md = new StringBuilder();
        md.append("# cardano-blueprint ledger conformance vectors\n\n");
        md.append("<!-- Generated by ledger-conformance BlueprintVectorGateTest "
                + "(./gradlew :ledger-conformance:conformanceReport). Do not edit by hand. -->\n\n");
        md.append("ADR-056 §8 and Phase 7b. The Java engine (`java-engine`: rule `LEDGER`, origin `SYNC`, Scalus phase 2) "
                + "replays every transaction of the cardano-blueprint ledger conformance vectors, Conway runs of the "
                + "Haskell ledger's Imp tests.\n\n");
        md.append("- **Vectors**: cardano-blueprint PR #71 (`").append(BlueprintVectorLoader.BLUEPRINT_REPOSITORY)
                .append("` at `").append(BlueprintVectorLoader.BLUEPRINT_COMMIT).append("`), `")
                .append(BlueprintVectorLoader.TARBALL_PATH).append("`, sha256 `")
                .append(BlueprintVectorLoader.TARBALL_SHA256).append("`; the same files as Amaru's ")
                .append("`crates/amaru-ledger/tests/data/rules-conformance` at tag `").append(ConformanceSettings.AMARU_TAG)
                .append("` (corpus digest `").append(BlueprintVectorLoader.CORPUS_DIGEST).append("`). ")
                .append("cardano-blueprint `main` (`0f0c17e1`) still carries the older JSON, one-transaction-per-file ")
                .append("tarball, which is a different format. The extracted vectors are vendored under ")
                .append("`ledger-conformance/vectors/cardano-blueprint` (its README has the pin and how to update it), ")
                .append("so the gate does not depend on PR #71's fork commit staying available.\n");
        md.append("- **Format**: `[config, initial NewEpochState, final NewEpochState, [event], title]`, ")
                .append("event `[0, tx, success, slot]` / `[1, slots]` (PassTick) / `[2, epochs]` (PassEpoch). A vector ")
                .append("records whether Haskell applied each transaction, not the predicate failure.\n");
        md.append("- **Harness**: the initial state is decoded into an `InMemoryLedgerView` (`NewEpochStateDecoder`, ")
                .append("fail closed); transactions run at their slot, the epoch under the vector's fixed epoch size, the ")
                .append("state's protocol version, the vector's network id and system start, and no forecast horizon ")
                .append("(the Imp tests' epoch info is fixed). Between transactions the state follows Haskell: an ")
                .append("applied transaction's effects go into an `OverlayLedgerView` (the engine's, or ")
                .append("`TxEffectsDeriver`'s for Haskell's verdict when the engine disagrees). **Tick and epoch events ")
                .append("are skipped**, as in Amaru: a disagreement in a transaction whose epoch is later than the initial ")
                .append("state's (`nesEL`) is `requires epoch`, not a failure. The boundary is taken from the state's ")
                .append("epoch, not from the events: one dump records a PassEpoch its initial state already includes.\n");
        md.append("- **Final-state check**: for a vector that stays in one epoch with unchanged parameters, the state ")
                .append("reached is compared with the vector's final `NewEpochState` (UTxO, accounts, pools, DReps, ")
                .append("committee, proposals): it checks the effects the Java side derives. It is not full-state ")
                .append("equality: votes, proposal payloads beyond type and parent, anchors, pool parameter bodies ")
                .append("beyond deposit, VRF key and retirement, deposit/fee/donation totals, the stake distribution and ")
                .append("snapshots are not compared (the rules do not read them); the treasury, enacted roots and ")
                .append("dormant-epoch count are not compared because only an epoch boundary changes them.\n\n");

        md.append("## Summary\n\n");
        md.append("| Imp spec | PV | Vectors | Transactions | passed | failed | requires epoch | undecodable |\n");
        md.append("|---|---:|---:|---:|---:|---:|---:|---:|\n");
        int[] totals = new int[6];
        for (Map.Entry<String, List<BlueprintVectorRunner.VectorResult>> e : byGroup(results).entrySet()) {
            String[] key = e.getKey().split(" PV ");
            int[] c = counts(e.getValue());
            for (int i = 0; i < c.length; i++) {
                totals[i] += c[i];
            }
            md.append("| ").append(key[0]).append(" | ").append(key[1]).append(" | ").append(c[0]).append(" | ")
                    .append(c[1]).append(" | ").append(c[2]).append(" | ").append(c[3]).append(" | ").append(c[4])
                    .append(" | ").append(c[5]).append(" |\n");
        }
        md.append("| **Total** | | **").append(totals[0]).append("** | **").append(totals[1]).append("** | **")
                .append(totals[2]).append("** | **").append(totals[3]).append("** | **").append(totals[4])
                .append("** | **").append(totals[5]).append("** |\n\n");
        md.append("Every vector runs in the Conway era; the first column is the Imp spec the test comes from. The ")
                .append("`ConwayImpSpec` tests run at protocol version 10, the others at 9 (the bootstrap phase).\n\n");

        long txs = results.stream().mapToLong(r -> r.transactions().size()).sum();
        long matched = results.stream().flatMap(r -> r.transactions().stream())
                .filter(BlueprintVectorRunner.TxResult::matches).count();
        long mismatchedBefore = results.stream().flatMap(r -> r.transactions().stream())
                .filter(t -> !t.matches() && !t.afterBoundary()).count();
        md.append("Transactions: ").append(txs).append(" replayed, ").append(matched).append(" with Haskell's verdict, ")
                .append(txs - matched).append(" not (").append(mismatchedBefore)
                .append(" of them before any skipped epoch boundary).\n\n");

        md.append("## Comparison with Amaru\n\n");
        md.append("Amaru's harness (`evaluate_ledger_states.rs`) records ").append(amaruFailures.size())
                .append(" known failures (`rules-conformance.failures.toml` at `").append(ConformanceSettings.AMARU_TAG)
                .append("`); it passes the other ").append(results.size() - amaruFailures.size())
                .append(" vectors. The gate requires the Java engine to pass every vector Amaru passes, unless the ")
                .append("exception is recorded below.\n\n");
        md.append("| Vector | Amaru | Java | Note |\n|---|---|---|---|\n");
        for (BlueprintVectorRunner.VectorResult r : results) {
            String id = r.vector().id();
            boolean amaruPasses = !amaruFailures.contains(id);
            boolean javaPasses = r.status() == BlueprintVectorRunner.Status.PASSED;
            if (amaruPasses && javaPasses) {
                continue;
            }
            Recorded rec = recorded.get(id);
            md.append("| `").append(id).append("` | ").append(amaruPasses ? "pass" : "fail").append(" | ")
                    .append(label(r.status())).append(" | ")
                    .append(rec != null ? "**" + rec.kind() + "**: " + escape(rec.evidence())
                            : javaPasses ? "Java passes a vector Amaru fails" : escape(r.reason()))
                    .append(" |\n");
        }
        md.append("\n");

        md.append("## Vectors the Java engine does not pass\n\n");
        md.append("| Vector | PV | Status | First disagreement |\n|---|---:|---|---|\n");
        for (BlueprintVectorRunner.VectorResult r : results) {
            if (r.status() != BlueprintVectorRunner.Status.PASSED) {
                md.append("| `").append(r.vector().id()).append("` | ").append(r.protocolMajor()).append(" | ")
                        .append(label(r.status())).append(" | ").append(escape(r.reason())).append(" |\n");
            }
        }
        md.append("\n");

        md.append("## Final-state check\n\n");
        Map<String, Integer> checks = new TreeMap<>();
        for (BlueprintVectorRunner.VectorResult r : results) {
            BlueprintVectorRunner.StateCheck check = r.stateCheck();
            String key = check.outcome() == BlueprintVectorRunner.StateCheck.Outcome.NOT_APPLICABLE
                    ? "not applicable: " + check.differences().getFirst().replaceAll("\\d+", "N")
                    : check.outcome().name().toLowerCase().replace('_', ' ');
            checks.merge(key, 1, Integer::sum);
        }
        md.append("| Outcome | Vectors |\n|---|---:|\n");
        checks.forEach((k, v) -> md.append("| ").append(k).append(" | ").append(v).append(" |\n"));
        md.append("\nAn Imp test can change the state without an event (`modifyPParams`): in the vectors listed as ")
                .append("\"protocol parameters changed outside the events\" the final parameters differ from the initial ")
                .append("ones although no epoch passed, so their transactions were validated against the initial ")
                .append("parameters: ");
        md.append(String.join(", ", results.stream()
                .filter(r -> r.stateCheck().paramsChangedOutsideEvents())
                .map(r -> "`" + r.vector().id() + "` (" + label(r.status()) + "; java rejects "
                        + r.transactions().stream().filter(t -> !t.observation().valid())
                        .map(t -> "tx " + t.index() + " with `" + t.observation().label() + "`").toList() + ")")
                .toList()));
        md.append(". In the three `no-cost-model` vectors the verdict matches for another reason: the failing "
                + "transaction was built against parameters without the script's cost model. `BlueprintVectorGateTest` validates the failing transaction of the "
                + "three `no-cost-model` vectors against their final state, whose parameters hold no cost model at all: "
                + "the Java engine reports Haskell's `UTXOS.CollectErrors [NoCostModel]` and nothing else, so the script "
                + "integrity hash matches and `PPViewHashesDontMatch` is an artefact of the missing event. (Before "
                + "Phase 7b, `ScriptIntegrity.costModel` read the empty cost-model map as unavailable and failed closed "
                + "with `ENGINE.LedgerStateUnavailable`; an empty raw map now means \"no cost model for any language\", "
                + "and only a `null` one, or an empty one beside a non-empty named map, is unavailable.)\n\n");
        results.stream().filter(r -> r.stateCheck().outcome() == BlueprintVectorRunner.StateCheck.Outcome.DIFFERS)
                .forEach(r -> md.append("- `").append(r.vector().id()).append("`: ")
                        .append(escape(String.join("; ", r.stateCheck().differences()))).append("\n"));

        md.append("## Decoder coverage\n\n");
        long initialOk = results.stream().filter(r -> r.status() != BlueprintVectorRunner.Status.UNDECODABLE).count();
        long finalOk = run.finalStates().stream().filter(NewEpochStateDecoder.Decoded::ok).count();
        md.append("Initial states decoded: ").append(initialOk).append(" of ").append(results.size())
                .append("; final states: ").append(finalOk).append(" of ").append(run.finalStates().size())
                .append(". Parts populated (vectors whose initial / final state has entries):\n\n");
        Map<String, int[]> parts = new TreeMap<>();
        results.forEach(r -> r.populated().keySet().forEach(k -> parts.computeIfAbsent(k, x -> new int[2])[0]++));
        run.finalStates().forEach(f -> f.populated().keySet().forEach(k -> parts.computeIfAbsent(k, x -> new int[2])[1]++));
        md.append("| Part | initial | final |\n|---|---:|---:|\n");
        parts.forEach((k, v) -> md.append("| ").append(k).append(" | ").append(v[0]).append(" | ").append(v[1])
                .append(" |\n"));
        List<String> notes = new ArrayList<>();
        run.finalStates().forEach(f -> notes.addAll(f.notes()));
        md.append("\nNot read (skipped by item boundaries): blocks made, snapshots, the reward pulser, the pool ")
                .append("distribution, the DRep pulser, genesis delegations, MIR pots, deposits/fees/donation totals. ")
                .append("The vectors use the CBOR `TxIn`/`TxOut` encoding for the UTxO and the `UMap` account layout; ")
                .append("a MemPack-encoded UTxO or the later `PState` layout would fail closed. Rounded rationals ")
                .append("(read only by the epoch boundary): ").append(notes.isEmpty() ? "none" : notes.stream()
                        .distinct().toList()).append(".\n\n");

        md.append("## Verdict-level constructor evidence\n\n");
        md.append("Transactions Haskell rejected, before any skipped epoch boundary, grouped by the Java engine's first ")
                .append("failure. The vectors do not carry Haskell's constructor, so this is the engine's name for a ")
                .append("rejection Haskell agrees with, not a constructor match.\n\n");
        md.append("| Constructor | Transactions (per PV) |\n|---|---|\n");
        run.rejectionEvidence().forEach((constructor, perPv) -> {
            List<String> parts2 = new ArrayList<>();
            perPv.forEach((pv, n) -> parts2.add("PV " + pv + ": " + n));
            md.append("| `").append(constructor).append("` | ").append(String.join(", ", parts2)).append(" |\n");
        });
        md.append("\nRejections reported as `ENGINE.*` where Haskell also rejects, listed for review. A decoding ")
                .append("failure is Haskell's verdict too when its decoder refuses the bytes: from Allegra on, a metadata ")
                .append("text or byte string over 64 bytes does not decode (`Metadata.hs:153-185` at the pin).\n\n");
        results.forEach(r -> r.transactions().stream()
                .filter(t -> !t.expected() && !t.observation().valid()
                        && "ENGINE".equals(t.observation().first().rule()))
                .forEach(t -> md.append("- `").append(r.vector().id()).append("` ").append(escape(t.describe()))
                        .append("\n")));
        return md.toString();
    }

    /** The Imp specs in era order. */
    private static final List<String> GROUPS = List.of("shelley", "allegra", "mary", "alonzo", "babbage", "conway");

    /** @return the results per Imp spec and protocol version ({@code conway PV 10}), in era order */
    public static Map<String, List<BlueprintVectorRunner.VectorResult>> byGroup(
            List<BlueprintVectorRunner.VectorResult> results) {
        Map<String, List<BlueprintVectorRunner.VectorResult>> grouped = new TreeMap<>((a, b) -> {
            int order = Integer.compare(groupIndex(a), groupIndex(b));
            return order != 0 ? order : a.compareTo(b);
        });
        results.forEach(r -> grouped.computeIfAbsent(r.vector().group() + " PV " + r.protocolMajor(),
                k -> new ArrayList<>()).add(r));
        return grouped;
    }

    private static int groupIndex(String key) {
        int index = GROUPS.indexOf(key.substring(0, key.indexOf(' ')));
        return index < 0 ? GROUPS.size() : index;
    }

    /** @return {vectors, transactions, passed, failed, requires epoch, undecodable or unsupported} */
    public static int[] counts(List<BlueprintVectorRunner.VectorResult> results) {
        int[] c = new int[6];
        for (BlueprintVectorRunner.VectorResult r : results) {
            c[0]++;
            c[1] += r.transactions().size();
            switch (r.status()) {
                case PASSED -> c[2]++;
                case FAILED -> c[3]++;
                case REQUIRES_EPOCH -> c[4]++;
                case UNDECODABLE, UNSUPPORTED_VERSION -> c[5]++;
            }
        }
        return c;
    }

    static String label(BlueprintVectorRunner.Status status) {
        return status.name().toLowerCase().replace('_', ' ');
    }

    private static String escape(String text) {
        return text.replace("|", "\\|").replace("\n", " ");
    }
}
