package org.yanoproject.ledger.conformance.report;

import org.yanoproject.ledger.conformance.ConformanceSettings;
import org.yanoproject.ledger.conformance.mutation.Mutation;
import org.yanoproject.ledger.conformance.mutation.Mutations;
import org.yanoproject.ledger.conformance.runner.CaseResult;
import org.yanoproject.ledger.conformance.runner.ConformanceCase;
import org.yanoproject.ledger.conformance.runner.ConformanceEngine;
import org.yanoproject.ledger.conformance.runner.Observation;
import org.yanoproject.ledger.rules.fixtures.conformance.ConwayConstructorCatalogue;
import org.yanoproject.ledger.rules.fixtures.conformance.ConwayConstructorCatalogue.Entry;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.Predicate;

/**
 * Renders the ADR-056 Phase 2 baseline ({@code ledger-conformance/docs/baseline-2026-09.md}): per engine, the Amaru
 * scenario verdict and constructor matches, the mutation matrix, a per-rule-family breakdown, the constructors each
 * engine demonstrably reports, and every mismatch.
 */
public final class BaselineReport {

    /** One engine's results. */
    public record EngineRun(ConformanceEngine engine, List<CaseResult> scenarios, List<CaseResult> mutations) {
    }

    private static final List<String> FAMILIES = List.of("PASS", "DECODING", "MEMPOOL", "LEDGER", "CERTS", "DELEG",
            "POOL", "GOVCERT", "GOV", "UTXOW", "UTXO", "UTXOS");

    private final List<EngineRun> runs;
    private final int scenarioCount;
    private final ConwayConstructorCatalogue catalogue = ConwayConstructorCatalogue.get();

    public BaselineReport(List<EngineRun> runs) {
        this.runs = List.copyOf(runs);
        this.scenarioCount = runs.isEmpty() ? 0 : runs.getFirst().scenarios().size();
    }

    public String toMarkdown() {
        StringBuilder md = new StringBuilder();
        header(md);
        summary(md);
        if (scenarioCount > 0) {
            families(md);
        }
        mutations(md);
        constructors(md);
        if (scenarioCount > 0) {
            causes(md);
            referenceDisagreements(md);
            mismatches(md);
        }
        return md.toString();
    }

    // --------------------------------------------------------------------------------------------- sections

    private void header(StringBuilder md) {
        md.append("# ADR-056 Phase 2 baseline (2026-09)\n\n");
        md.append("<!-- Generated by ledger-conformance ConformanceBaselineTest "
                + "(./gradlew :ledger-conformance:conformanceReport). Do not edit by hand. -->\n\n");
        md.append("Generated ").append(LocalDate.now()).append(" by\n\n```\n./gradlew :ledger-conformance:conformanceReport "
                + "-PwithAmaru=true -PamaruWasm=<amaru_validator.wasm> -PamaruScenariosDir=<amaru clone at "
                + ConformanceSettings.AMARU_TAG + ">\n```\n\n");
        md.append("Measured, not estimated (ADR-056 §8, Phase 2). The baseline is informational: engines are expected ")
                .append("to disagree with Haskell, and nothing here gates the build.\n\n");
        md.append("- **Scenarios**: ").append(scenarioCount == 0 ? "not configured"
                        : scenarioCount + " Haskell-cross-checked Amaru scenarios (tag `" + ConformanceSettings.AMARU_TAG + "`)")
                .append(", rule `LEDGER`, origin `SYNC`, one `InMemoryLedgerView` per scenario.\n");
        md.append("- **Mutants**: ").append(Mutations.all().size())
                .append(" mutants (single faults, or Haskell's whole failure list where a fault always has several) of ")
                .append(Mutation.Base.values().length).append(" valid base transactions (preprod-like PV 10 world, ")
                .append("signed with Amaru's corpus test keys, re-signed after every edit).\n");
        md.append("- **Constructors**: ").append(catalogue.all().size()).append(" Conway leaf predicate failures at ")
                .append("cardano-ledger `").append(catalogue.cardanoLedger()).append("`, ")
                .append(catalogue.inScope().size()).append(" reachable at PV 10–11 ")
                .append("([coverage matrix](../../ledger-rules/docs/conway-rule-coverage.md)).\n");
        md.append("- **Verdict match**: accepted exactly when Haskell accepts. **Constructor match**: the verdict matches ")
                .append("and the engine's *first* failure is the expected Haskell `RULE.Constructor` (a decoding failure ")
                .append("must be reported as one). **Constructor found**: the expected constructor is among the engine's ")
                .append("failures in any position (the copied Java rules report every failure, in their own order).\n\n");
        md.append("| Engine | What runs |\n|---|---|\n");
        runs.forEach(r -> md.append("| `").append(r.engine().name()).append("` | ").append(r.engine().description())
                .append(" |\n"));
        md.append('\n');
    }

    private void summary(StringBuilder md) {
        md.append("## Summary\n\n");
        md.append("| Engine | Scenarios: verdict | Scenarios: constructor | Scenarios: constructor found | ")
                .append("Mutants: constructor | Bases valid | Constructors demonstrated | ms / scenario (one pass) |\n");
        md.append("|---|---:|---:|---:|---:|---:|---:|---:|\n");
        int mutants = Mutations.all().size();
        for (EngineRun run : runs) {
            List<CaseResult> mutantResults = mutants(run);
            List<CaseResult> bases = run.mutations().stream()
                    .filter(r -> r.testCase().kind() == ConformanceCase.Kind.MUTATION_BASE).toList();
            md.append("| `").append(run.engine().name()).append("` | ")
                    .append(ratio(run.scenarios(), CaseResult::verdictMatch)).append(" | ")
                    .append(ratio(run.scenarios(), CaseResult::constructorMatch)).append(" | ")
                    .append(ratio(run.scenarios(), CaseResult::constructorFound)).append(" | ")
                    .append(count(mutantResults, CaseResult::constructorMatch)).append('/').append(mutants).append(" | ")
                    .append(count(bases, CaseResult::verdictMatch)).append('/').append(bases.size()).append(" | ")
                    .append(demonstrated(run).size()).append('/').append(catalogue.inScope().size()).append(" | ")
                    .append(run.scenarios().isEmpty() ? "–" : String.format(Locale.ROOT, "%.2f",
                            run.scenarios().stream().mapToDouble(CaseResult::millis).average().orElse(0)))
                    .append(" |\n");
        }
        md.append("\n*Constructors demonstrated*: in-scope constructors the engine reports first on at least one ")
                .append("scenario or mutant that expects them (where Haskell always reports a fault with several ")
                .append("constructors, any of them counts). The scenarios and mutants can demonstrate ")
                .append(demonstrable().size()).append(" of the ").append(catalogue.inScope().size())
                .append(" constructors; the rest need Phase 3–5 mutants.\n\n");
    }

    private void families(StringBuilder md) {
        md.append("## Scenarios per rule family\n\n");
        md.append("Verdict matches / constructor matches, by the rule family of the expected constructor ")
                .append("(`PASS`: expected valid; `DECODING`: expected not to decode).\n\n");
        md.append("| Family | Scenarios |");
        runs.forEach(r -> md.append(" `").append(r.engine().name()).append("` |"));
        md.append("\n|---|---:|");
        runs.forEach(r -> md.append("---:|"));
        md.append('\n');
        for (String family : FAMILIES) {
            List<Integer> indexes = new ArrayList<>();
            List<CaseResult> first = runs.getFirst().scenarios();
            for (int i = 0; i < first.size(); i++) {
                if (first.get(i).testCase().family().equals(family)) {
                    indexes.add(i);
                }
            }
            if (indexes.isEmpty()) {
                continue;
            }
            md.append("| ").append(family).append(" | ").append(indexes.size()).append(" |");
            for (EngineRun run : runs) {
                List<CaseResult> rows = indexes.stream().map(i -> run.scenarios().get(i)).toList();
                md.append(' ').append(count(rows, CaseResult::verdictMatch)).append(" / ")
                        .append(count(rows, CaseResult::constructorMatch)).append(" |");
            }
            md.append('\n');
        }
        md.append('\n');
    }

    private void mutations(StringBuilder md) {
        md.append("## Mutation matrix\n\n");
        md.append("`✓`: the expected verdict and constructor; otherwise the engine's first failure (or `Valid`).\n\n");
        md.append("| Case | Expected |");
        runs.forEach(r -> md.append(" `").append(r.engine().name()).append("` |"));
        md.append("\n|---|---|");
        runs.forEach(r -> md.append("---|"));
        md.append('\n');
        int rows = runs.isEmpty() ? 0 : runs.getFirst().mutations().size();
        for (int i = 0; i < rows; i++) {
            ConformanceCase testCase = runs.getFirst().mutations().get(i).testCase();
            md.append("| `").append(testCase.id()).append("` | ").append(testCase.expectedLabel()).append(" |");
            for (EngineRun run : runs) {
                CaseResult result = run.mutations().get(i);
                md.append(' ').append(result.constructorMatch() ? "✓" : "`" + result.observation().label() + "`")
                        .append(" |");
            }
            md.append('\n');
        }
        md.append("\nMutants (").append(Mutations.all().size()).append("):\n\n");
        for (Mutation mutation : Mutations.all()) {
            md.append("- `").append(mutation.id()).append("` → `").append(mutation.covers()).append("`: ")
                    .append(mutation.description()).append('\n');
        }
        md.append('\n');
    }

    private void constructors(StringBuilder md) {
        md.append("## Constructors demonstrated per engine\n\n");
        md.append("In-scope constructors that at least one scenario or mutant expects, with the engines that report ")
                .append("them as Haskell does (first failure). Constructors no case expects are gaps of the corpus ")
                .append("and the mutation matrix, listed after the table.\n\n");
        md.append("| Constructor | Cases |");
        runs.forEach(r -> md.append(" `").append(r.engine().name()).append("` |"));
        md.append("\n|---|---:|");
        runs.forEach(r -> md.append("---|"));
        md.append('\n');
        Map<String, Integer> cases = expectedCounts();
        List<Set<String>> perEngine = runs.stream().map(this::demonstrated).toList();
        for (Entry entry : catalogue.inScope()) {
            Integer n = cases.get(entry.qualifiedName());
            if (n == null) {
                continue;
            }
            md.append("| `").append(entry.qualifiedName()).append("` | ").append(n).append(" |");
            for (Set<String> demonstrated : perEngine) {
                md.append(demonstrated.contains(entry.qualifiedName()) ? " ✓ |" : " ✗ |");
            }
            md.append('\n');
        }
        md.append("| **Total** | |");
        perEngine.forEach(d -> md.append(" **").append(d.size()).append("** |"));
        md.append("\n\nNo scenario or mutant expects (").append(catalogue.inScope().size() - cases.size())
                .append("): ");
        md.append(String.join(", ", catalogue.inScope().stream().map(Entry::qualifiedName)
                .filter(n -> !cases.containsKey(n)).map(n -> "`" + n + "`").toList()));
        md.append(".\n\n");
    }

    private void causes(StringBuilder md) {
        md.append("## Main causes of constructor mismatches\n\n");
        md.append("Scenario constructor mismatches grouped by what the engine reported first (top 8 per engine).\n\n");
        for (EngineRun run : runs) {
            Map<String, List<CaseResult>> byReported = new LinkedHashMap<>();
            run.scenarios().stream().filter(r -> !r.constructorMatch())
                    .forEach(r -> byReported.computeIfAbsent(r.observation().label(), k -> new ArrayList<>()).add(r));
            if (byReported.isEmpty()) {
                continue;
            }
            md.append("**`").append(run.engine().name()).append("`** (")
                    .append(byReported.values().stream().mapToInt(List::size).sum()).append(" mismatches)\n\n");
            md.append("| Reported first | Count | Expected (examples) |\n|---|---:|---|\n");
            byReported.entrySet().stream()
                    .sorted((a, b) -> Integer.compare(b.getValue().size(), a.getValue().size()))
                    .limit(8)
                    .forEach(e -> {
                        Set<String> expected = new TreeSet<>();
                        e.getValue().forEach(r -> expected.add(r.testCase().expectedLabel()));
                        List<String> shown = expected.stream().limit(4).toList();
                        md.append("| `").append(e.getKey()).append("` | ").append(e.getValue().size()).append(" | ")
                                .append(String.join(", ", shown))
                                .append(expected.size() > shown.size() ? ", … (" + expected.size() + " kinds)" : "")
                                .append(" |\n");
                    });
            md.append('\n');
        }
    }

    private void referenceDisagreements(StringBuilder md) {
        runs.stream().filter(r -> r.engine().name().equals("amaru")).findFirst().ifPresent(amaru -> {
            md.append("## Reference engine vs Haskell\n\n");
            List<CaseResult> misses = amaru.scenarios().stream().filter(r -> !r.constructorMatch()).toList();
            if (misses.isEmpty()) {
                md.append("Amaru matches every scenario.\n\n");
                return;
            }
            md.append("Scenarios where the Amaru engine's first failure differs from the expected Haskell ")
                    .append("constructor:\n\n");
            for (CaseResult miss : misses) {
                md.append("- `").append(miss.testCase().id()).append("`: expected ").append(miss.testCase().expectedLabel())
                        .append(", got `").append(miss.observation().label()).append('`');
                if (miss.testCase().env().protocolMajor() < 10) {
                    md.append(" — protocol version ").append(miss.testCase().env().protocolMajor())
                            .append(": refused by design (ADR-056 invariant 6, PV 10+ only), not a disagreement");
                }
                md.append('\n');
            }
            md.append('\n');
        });
    }

    private void mismatches(StringBuilder md) {
        md.append("## Scenario mismatches per engine\n\n");
        for (EngineRun run : runs) {
            List<CaseResult> misses = run.scenarios().stream().filter(r -> !r.constructorMatch()).toList();
            md.append("<details><summary><code>").append(run.engine().name()).append("</code>: ")
                    .append(misses.size()).append(" of ").append(run.scenarios().size())
                    .append(" without a constructor match</summary>\n\n");
            if (!misses.isEmpty()) {
                md.append("| Scenario | Expected | Reported first | Engine detail |\n|---|---|---|---|\n");
                for (CaseResult miss : misses) {
                    Observation.Failure first = miss.observation().first();
                    md.append("| ").append(miss.testCase().id()).append(" | ").append(miss.testCase().expectedLabel())
                            .append(" | `").append(miss.observation().label()).append("` | ")
                            .append(first == null ? "" : cell(first.raw())).append(" |\n");
                }
            }
            md.append("\n</details>\n\n");
        }
    }

    // --------------------------------------------------------------------------------------------- helpers

    private static List<CaseResult> mutants(EngineRun run) {
        return run.mutations().stream().filter(r -> r.testCase().kind() == ConformanceCase.Kind.MUTANT).toList();
    }

    /**
     * @return the in-scope constructors an engine reported first on some scenario or mutant that expects them (for
     *         a fault Haskell reports with several constructors, the one the engine reported)
     */
    public Set<String> demonstrated(EngineRun run) {
        Set<String> names = new LinkedHashSet<>();
        List<CaseResult> all = new ArrayList<>(run.scenarios());
        all.addAll(run.mutations());
        for (CaseResult result : all) {
            if (result.testCase().expectedConstructor() != null && result.constructorMatch()) {
                String reported = result.observation().first().qualifiedName();
                if (catalogue.find(reported).map(Entry::inScope).orElse(false)) {
                    names.add(reported);
                }
            }
        }
        return names;
    }

    /** @return in-scope constructors some case expects (including the other constructors of a Haskell list) */
    private Set<String> demonstrable() {
        return expectedCounts().keySet();
    }

    private Map<String, Integer> expectedCounts() {
        Map<String, Integer> counts = new LinkedHashMap<>();
        if (runs.isEmpty()) {
            return counts;
        }
        List<CaseResult> all = new ArrayList<>(runs.getFirst().scenarios());
        all.addAll(runs.getFirst().mutations());
        for (CaseResult result : all) {
            for (String expected : result.testCase().acceptedFirst()) {
                if (catalogue.find(expected).map(Entry::inScope).orElse(false)) {
                    counts.merge(expected, 1, Integer::sum);
                }
            }
        }
        return counts;
    }

    private static String ratio(List<CaseResult> results, Predicate<CaseResult> test) {
        return results.isEmpty() ? "–" : count(results, test) + "/" + results.size();
    }

    private static long count(List<CaseResult> results, Predicate<CaseResult> test) {
        return results.stream().filter(test).count();
    }

    private static String cell(String text) {
        return Observation.abbreviate(text).replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;");
    }
}
