import { describe, expect, it } from 'vitest';
import {
  assertAuthMapEnvelope, assertPendingEnvelope, authorizationLabel, decodeCbor,
  decodeEntryRecordValue, directSubmitAllowed, encodeBasicEnvelopeHex, encodeCommandHex,
  governedCliHint,
  hexToBytes, isAuthenticatedMapChain, OP_COMPARE_AND_SET, OP_PUT, OP_REVOKE,
  OP_TRANSFER_CONTROLLER, preflightMutation, receiptErrorLabel, utf8ToHex
} from './model';
import type { AuthMapCollection, AuthMapEnvelope } from '$lib/api/types';

const PRODUCTS: AuthMapCollection = {
  id: 'products', authorization: 1, authorizationPolicy: '', restoreAllowed: false,
  maxKeyBytes: 64, maxValueBytes: 4096, valueEncoding: 1, validator: 'product-v1'
};

const put = (overrides: Record<string, unknown> = {}) => ({
  operation: OP_PUT, collectionId: 'products', keyHex: utf8ToHex('key'),
  valueHex: '82a1611601', expectedRevision: 0, expectedValueHashHex: '',
  newControllerHex: '', ...overrides
});

describe('authenticated-map canonical command encoding', () => {
  // Golden vectors generated by the showcase codec (tools/showcase_codec.py),
  // which is contract-tested against AuthenticatedMapContract.
  it('matches the cross-language PUT command vector', () => {
    expect(encodeCommandHex([put()], [PRODUCTS]))
      .toBe('8301008187006870726f6475637473436b65794582a1611601004040');
  });

  it('matches the cross-language batch vector with a compare-and-set', () => {
    const cas = put({
      operation: OP_COMPARE_AND_SET, collectionId: 'attachments',
      keyHex: utf8ToHex('k2'), valueHex: utf8ToHex('v2'), expectedRevision: 3
    });
    expect(encodeCommandHex([put(), cas]))
      .toBe('8301018287006870726f6475637473436b65794582a161160100404087026b617474616368'
        + '6d656e7473426b32427632034040');
  });

  it('matches the cross-language revoke and transfer vectors', () => {
    expect(encodeCommandHex([put({ operation: OP_REVOKE, valueHex: '', expectedRevision: 4 })]))
      .toBe('8301008187046870726f6475637473436b657940044040');
    expect(encodeCommandHex([put({
      operation: OP_TRANSFER_CONTROLLER, collectionId: 'attachments',
      keyHex: utf8ToHex('k2'), valueHex: '', expectedRevision: 7,
      newControllerHex: '33'.repeat(32)
    })])).toBe('8301008187036b6174746163686d656e7473426b32400740'
      + '58203333333333333333333333333333333333333333333333333333333333333333');
  });

  it('matches the Java-pinned final submit envelope for basic collections', () => {
    // Same vector as ShowcaseAuthenticatedMapConfigTest and the packaged CLI:
    // [1, bytes([1, 0, [put], [[0, owner, "", 0]]]), []].
    expect(encodeBasicEnvelopeHex([put()], [PRODUCTS]))
      .toBe('830158228401008187006870726f6475637473436b6579'
        + '4582a161160100404081840001600080');
    expect(() => encodeBasicEnvelopeHex([put()], [{ ...PRODUCTS, authorization: 3 }]))
      .toThrow('externally signed');
    expect(() => encodeBasicEnvelopeHex([put({ collectionId: 'missing' })], [PRODUCTS]))
      .toThrow('externally signed');
  });

  it('rejects duplicate batch keys, empty batches, and out-of-bound values', () => {
    expect(() => encodeCommandHex([])).toThrow('1-128');
    expect(() => encodeCommandHex([put(), put()])).toThrow('duplicate');
    expect(() => preflightMutation(put({ valueHex: 'ff'.repeat(5000) }), PRODUCTS))
      .toThrow('collection bound');
    expect(() => preflightMutation(put({ expectedRevision: 2 }))).toThrow('precondition');
    expect(() => preflightMutation(put({
      operation: OP_COMPARE_AND_SET, expectedRevision: 0
    }))).toThrow('Compare-and-set');
    expect(() => preflightMutation(put({ operation: 9 }))).toThrow('Unsupported');
  });
});

describe('authenticated-map entry decoding', () => {
  it('decodes the canonical entry record value', () => {
    const entry = decodeEntryRecordValue('8801000258201111111111111111111111111111111111111111'
      + '111111111111111111111111'
      + '4582a16116015820222222222222222222222222222222222222222222222222222222222222222205'
      + '09');
    expect(entry).toEqual({
      status: 0, revision: 2, controllerHex: '11'.repeat(32), valueHex: '82a1611601',
      logicalValueHashHex: '22'.repeat(32), createdHeight: 5, lastMutationHeight: 9
    });
  });

  it('rejects non-entry payloads and unsupported CBOR', () => {
    expect(() => decodeEntryRecordValue('820102')).toThrow('canonical');
    expect(() => decodeCbor(hexToBytes('a1616b01'))).toThrow('unsupported major type');
    expect(() => decodeCbor(hexToBytes('8301'))).toThrow('truncated');
  });
});

describe('authenticated-map envelope identity gates', () => {
  const envelope: AuthMapEnvelope<unknown> = {
    apiVersion: 'authenticated-map-domain-v1', chainId: 'map-chain',
    stateMachineId: 'authenticated-map', committedHeight: 7, stateRoot: 'aa'.repeat(32),
    proofKey: '01', recordValue: '02', verificationLevel: 'authenticated-record',
    record: {}
  };

  it('accepts a matching exact-record envelope and rejects identity drift', () => {
    expect(() => assertAuthMapEnvelope(envelope, 'map-chain')).not.toThrow();
    expect(() => assertAuthMapEnvelope({ ...envelope, chainId: 'other' }, 'map-chain')).toThrow();
    expect(() => assertAuthMapEnvelope({ ...envelope, stateMachineId: 'eutxo-ledger' },
      'map-chain')).toThrow();
    expect(() => assertAuthMapEnvelope({ ...envelope, apiVersion: 'v2' }, 'map-chain')).toThrow();
    expect(() => assertAuthMapEnvelope({ ...envelope, verificationLevel: 'derived' },
      'map-chain')).toThrow();
  });

  it('requires role-workflow envelopes to omit apiVersion', () => {
    const role = { ...envelope, apiVersion: undefined, verificationLevel: undefined };
    expect(() => assertAuthMapEnvelope(role, 'map-chain', false)).not.toThrow();
    expect(() => assertAuthMapEnvelope(envelope, 'map-chain', false)).toThrow();
  });

  it('requires the derived label and source index key on pending pages', () => {
    const pending: AuthMapEnvelope<unknown> = {
      apiVersion: 'authenticated-map-domain-v1', chainId: 'map-chain',
      stateMachineId: 'authenticated-map', committedHeight: 7, stateRoot: 'aa'.repeat(32),
      sourceIndexProofKey: '01', queryValue: '02',
      verificationLevel: 'DERIVED_FROM_PENDING_INDEX', record: {}
    };
    expect(() => assertPendingEnvelope(pending, 'map-chain')).not.toThrow();
    expect(() => assertPendingEnvelope({ ...pending, verificationLevel: 'authenticated-record' },
      'map-chain')).toThrow();
    expect(() => assertPendingEnvelope({ ...pending, proofKey: '0a' }, 'map-chain')).toThrow();
  });
});

describe('capability and labelling helpers', () => {
  it('detects the state machine and direct-submit authorization modes', () => {
    const manifest = {
      schemaVersion: 1, applicationId: 'custom-map', applicationVersion: '1',
      manifestDigest: 'aa'.repeat(32),
      components: [{ id: 'authenticated-map', version: '1', configurationId: 'demo',
        stateNamespace: 'application/v1', topics: [], querySubjects: [], origin: 'COMPOSED' as const }],
      workflows: [], crossCutting: [], proofSubjects: []
    };
    expect(isAuthenticatedMapChain({ stateMachine: 'custom', capabilityManifest: manifest })).toBe(true);
    expect(isAuthenticatedMapChain({ stateMachine: 'authenticated-map' })).toBe(false);
    expect(directSubmitAllowed(PRODUCTS)).toBe(true);
    expect(directSubmitAllowed({ ...PRODUCTS, authorization: 3 })).toBe(false);
    expect(directSubmitAllowed(undefined)).toBe(false);
  });

  it('labels enums and receipt errors', () => {
    expect(authorizationLabel(3)).toBe('governed-role');
    expect(receiptErrorLabel(27)).toBe('wrong-revision');
    expect(receiptErrorLabel(99)).toBe('unknown(99)');
  });

  it('produces the offline signing CLI hint without any key material', () => {
    const hint = governedCliHint('83010081', { ...PRODUCTS, authorization: 3,
      authorizationPolicy: 'issuer-write' });
    expect(hint).toContain('authenticated-map action');
    expect(hint).toContain('--command-hex 83010081');
    expect(hint).toContain('0:governed-role:issuer-write:1');
  });
});
