#!/usr/bin/env bash
# Package the built module for publication (ADR-057 §3):
#
#   scripts/bundle.sh <version>        # after scripts/build-wasm.sh
#
# Writes to target/publish/ (under $CARGO_TARGET_DIR when set):
#   amaru-validator-wasm-<version>.tar.gz          the bundle
#   amaru-validator-wasm-<version>.tar.gz.sha256
#   amaru_validator.wasm, amaru_validator.wasm.sha256   the module on its own
#
# The bundle holds amaru_validator.wasm and its .sha256, AMARU_VERSION, NOTICE, LICENSE-AMARU,
# INTERFACE.md and THIRD-PARTY-LICENSES.txt, generated by cargo-about (`$CARGO_ABOUT`, else
# `cargo-about` on PATH) from Cargo.lock for the wasm32-wasip1 graph.
set -euo pipefail

VERSION="${1:?usage: scripts/bundle.sh <version>}"
[[ "$VERSION" =~ ^[0-9A-Za-z._+-]+$ ]] || { echo "invalid version: $VERSION" >&2; exit 1; }

CRATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="${CARGO_TARGET_DIR:-$CRATE_DIR/target}"
WASM_OUT="$TARGET_DIR/wasm-out"
PUBLISH="$TARGET_DIR/publish"
NAME="amaru-validator-wasm-$VERSION"
CARGO_ABOUT="${CARGO_ABOUT:-cargo-about}"

cd "$CRATE_DIR"
[[ -f "$WASM_OUT/amaru_validator.wasm" ]] || { echo "run scripts/build-wasm.sh first" >&2; exit 1; }
(cd "$WASM_OUT" && if command -v sha256sum >/dev/null; then sha256sum -c amaru_validator.wasm.sha256; else shasum -a 256 -c amaru_validator.wasm.sha256; fi)
command -v "$CARGO_ABOUT" >/dev/null || { echo "cargo-about not found (set CARGO_ABOUT)" >&2; exit 1; }

rm -rf "$PUBLISH"
mkdir -p "$PUBLISH/$NAME"
cp "$WASM_OUT/amaru_validator.wasm" "$WASM_OUT/amaru_validator.wasm.sha256" \
   AMARU_VERSION NOTICE LICENSE-AMARU INTERFACE.md "$PUBLISH/$NAME/"
"$CARGO_ABOUT" generate --locked --fail about.hbs -o "$PUBLISH/$NAME/THIRD-PARTY-LICENSES.txt"

# Stable archive: sorted names, fixed owner and mtime (GNU tar; bsdtar ignores what it lacks).
if tar --version 2>/dev/null | grep -q 'GNU tar'; then
  tar --sort=name --owner=0 --group=0 --numeric-owner --mtime='@0' \
      -C "$PUBLISH" -czf "$PUBLISH/$NAME.tar.gz" "$NAME"
else
  tar -C "$PUBLISH" -czf "$PUBLISH/$NAME.tar.gz" "$NAME"
fi
cp "$WASM_OUT/amaru_validator.wasm" "$WASM_OUT/amaru_validator.wasm.sha256" "$PUBLISH/"

cd "$PUBLISH"
if command -v sha256sum >/dev/null; then
  sha256sum "$NAME.tar.gz" > "$NAME.tar.gz.sha256"
else
  shasum -a 256 "$NAME.tar.gz" > "$NAME.tar.gz.sha256"
fi
rm -rf "$NAME"
ls -l
cat "$NAME.tar.gz.sha256" amaru_validator.wasm.sha256
