config_ordinal=275
yano.app-chain.chains[0].state-machine=approvals
yano.app-chain.chains[0].effects.enabled=true
yano.app-chain.chains[0].machines.approvals.payments=true
yano.app-chain.chains[0].machines.approvals.activations.payments=1
yano.app-chain.chains[0].machines.approvals.payment-type=webhook.post
yano.app-chain.chains[0].machines.approvals.payment-gate=app-final
yano.app-chain.chains[0].effects.executor.enabled=true
yano.app-chain.chains[0].effects.executor.types=webhook.post
yano.app-chain.chains[0].effects.executors.webhook.url=http://127.0.0.1:8099/yano
yano.app-chain.chains[0].effects.executors.webhook.timeout-ms=5000
