Args = -march=compatibility \
       --enable-http \
       --enable-https \
       --enable-url-protocols=http,https \
       --enable-all-security-services \
       --initialize-at-build-time=com.fasterxml.jackson.annotation \
       --initialize-at-build-time=com.fasterxml.jackson.core \
       --initialize-at-build-time=com.fasterxml.jackson.databind \
       --initialize-at-run-time=org.slf4j \
       --initialize-at-run-time=com.bloxbean.cardano.client.transaction.spec.Transaction \
       --initialize-at-run-time=javafx.application.Platform \
       --initialize-at-run-time=com.sun.glass.ui.Application \
       --initialize-at-run-time=com.sun.javafx.tk.Toolkit
