package com.bloxbean.cardano.yano.api.appchain.effects;

/**
 * Terminal, consensus-recorded outcome of a {@link ResultPolicy#CHAIN} effect
 * (ADR app-layer/010 F8/F9). Terminal states are absorbing: the first
 * incorporated outcome wins; later results for the same effect are
 * deterministic no-ops.
 */
public enum EffectOutcome {

    /** The external action succeeded; {@code externalRef} carries the canonical handle. */
    CONFIRMED(1),

    /** The external system answered with a definitive failure (reason code in externalRef). */
    FAILED(2),

    /** Cancelled by an authorized member before execution completed. Cancel cannot unsend. */
    CANCELLED(3),

    /**
     * Nobody incorporated a result before the effect's expiry height passed —
     * the deterministic liveness escape hatch, generated by the framework
     * sweep, never by a message (ADR-010 F9).
     */
    EXPIRED(4);

    private final int code;

    EffectOutcome(int code) {
        this.code = code;
    }

    public int code() {
        return code;
    }

    public static EffectOutcome fromCode(int code) {
        return switch (code) {
            case 1 -> CONFIRMED;
            case 2 -> FAILED;
            case 3 -> CANCELLED;
            case 4 -> EXPIRED;
            default -> throw new IllegalArgumentException("Unknown effect outcome code: " + code);
        };
    }
}
