services:
  yano:
    environment:
      YANO_PROFILE: ${YANO_PROFILE:-devnet}
      YANO_NETWORK: ${YANO_NETWORK:-devnet}
    volumes:
      - ${YANO_CHAINSTATE_PATH:-../chainstate-devnet}:/app/chainstate
      - ${YANO_APPCHAIN_STATE_PATH:-../appchain-chainstate-devnet}:/app/appchain-chainstate
      - ${YANO_APPCHAIN_INDEXER_PATH:-../appchain-indexers-devnet}:/app/appchain-indexers
