services:
  yano:
    environment:
      YANO_PROFILE: ${YANO_PROFILE:-mainnet}
      YANO_NETWORK: ${YANO_NETWORK:-mainnet}
    volumes:
      - ${YANO_CHAINSTATE_PATH:-../chainstate-mainnet}:/app/chainstate
