services:
  yano:
    environment:
      YANO_PROFILE: ${YANO_PROFILE:-sanchonet}
      YANO_NETWORK: ${YANO_NETWORK:-sanchonet}
    volumes:
      - ${YANO_RUNTIME_DATA_PATH:-../data-sanchonet/runtime-data}:/app/data
      - ${YANO_CHAINSTATE_PATH:-../data-sanchonet/chainstate}:/app/data/chainstate
      - ${YANO_APPCHAIN_STATE_PATH:-../data-sanchonet/appchain-chainstate}:/app/appchain-chainstate
      - ${YANO_APPCHAIN_INDEXER_PATH:-../data-sanchonet/appchain-indexers}:/app/appchain-indexers
