package com.bloxbean.cardano.yano.api.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Epoch-scoped protocol parameters in Yano's domain model.
 */
public record ProtocolParamsSnapshot(
        int epoch,
        Integer minFeeA,
        Integer minFeeB,
        Integer maxBlockSize,
        Integer maxTxSize,
        Integer maxBlockHeaderSize,
        BigInteger keyDeposit,
        BigInteger poolDeposit,
        Integer eMax,
        Integer nOpt,
        BigDecimal a0,
        BigDecimal rho,
        BigDecimal tau,
        BigDecimal decentralisationParam,
        String extraEntropy,
        Integer protocolMajorVer,
        Integer protocolMinorVer,
        BigInteger minUtxo,
        BigInteger minPoolCost,
        String nonce,
        Map<String, LinkedHashMap<String, Long>> costModels,
        Map<String, List<Long>> costModelsRaw,
        BigDecimal priceMem,
        BigDecimal priceStep,
        BigInteger maxTxExMem,
        BigInteger maxTxExSteps,
        BigInteger maxBlockExMem,
        BigInteger maxBlockExSteps,
        BigInteger maxValSize,
        Integer collateralPercent,
        Integer maxCollateralInputs,
        BigInteger coinsPerUtxoSize,
        BigInteger coinsPerUtxoWord,
        BigDecimal pvtMotionNoConfidence,
        BigDecimal pvtCommitteeNormal,
        BigDecimal pvtCommitteeNoConfidence,
        BigDecimal pvtHardForkInitiation,
        BigDecimal pvtPPSecurityGroup,
        BigDecimal dvtMotionNoConfidence,
        BigDecimal dvtCommitteeNormal,
        BigDecimal dvtCommitteeNoConfidence,
        BigDecimal dvtUpdateToConstitution,
        BigDecimal dvtHardForkInitiation,
        BigDecimal dvtPPNetworkGroup,
        BigDecimal dvtPPEconomicGroup,
        BigDecimal dvtPPTechnicalGroup,
        BigDecimal dvtPPGovGroup,
        BigDecimal dvtTreasuryWithdrawal,
        Integer committeeMinSize,
        Integer committeeMaxTermLength,
        Integer govActionLifetime,
        BigInteger govActionDeposit,
        BigInteger drepDeposit,
        Integer drepActivity,
        BigDecimal minFeeRefScriptCostPerByte) {

    public ProtocolParamsSnapshot withEpoch(int epoch) {
        return new ProtocolParamsSnapshot(
                epoch,
                minFeeA,
                minFeeB,
                maxBlockSize,
                maxTxSize,
                maxBlockHeaderSize,
                keyDeposit,
                poolDeposit,
                eMax,
                nOpt,
                a0,
                rho,
                tau,
                decentralisationParam,
                extraEntropy,
                protocolMajorVer,
                protocolMinorVer,
                minUtxo,
                minPoolCost,
                nonce,
                costModels,
                costModelsRaw,
                priceMem,
                priceStep,
                maxTxExMem,
                maxTxExSteps,
                maxBlockExMem,
                maxBlockExSteps,
                maxValSize,
                collateralPercent,
                maxCollateralInputs,
                coinsPerUtxoSize,
                coinsPerUtxoWord,
                pvtMotionNoConfidence,
                pvtCommitteeNormal,
                pvtCommitteeNoConfidence,
                pvtHardForkInitiation,
                pvtPPSecurityGroup,
                dvtMotionNoConfidence,
                dvtCommitteeNormal,
                dvtCommitteeNoConfidence,
                dvtUpdateToConstitution,
                dvtHardForkInitiation,
                dvtPPNetworkGroup,
                dvtPPEconomicGroup,
                dvtPPTechnicalGroup,
                dvtPPGovGroup,
                dvtTreasuryWithdrawal,
                committeeMinSize,
                committeeMaxTermLength,
                govActionLifetime,
                govActionDeposit,
                drepDeposit,
                drepActivity,
                minFeeRefScriptCostPerByte);
    }
}
